### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by maxhis** [wangmchn/WMPageController-Swift#2]
首先非常感谢贡献这么好用的library！

在使用的过程中发现一个必现的crash：从`PageController`pop back时会crash：`fatal error: unexpectedly found nil while unwrapping an Optional value`，不确定是不是我使用上有什么疏漏，我用的是Storyboard。

具体出错代码是在MenuView.swift line 214：`let itemWidth = delegate!.menuView(self, widthForItemAtIndex: index)`

**Comment by maxhis** [comment]
#3 Fix之后这个问题也没有了，可以close。

**Comment by wangmchn** [comment]
Thanks!
