### ISSUE TITLE
Unable to dequeue a cell with identifier when embedded into WMPageController

### ISSUE THREAD

**Issue by maxhis** [wangmchn/WMPageController-Swift#3]
I am using `WMPageController` in storyboard. I have a customized `UITableViewController` with prototype cells, it works well when stand alone. But when embedded it into `WMPageController`, a crash happens. The error message is:`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier VoucherListCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'`.

Could you please to help find out what is going wrong? Thanks a lot.

**Comment by wangmchn** [comment]
Hi, @maxhis 
Thanks for your issue
Actually, the swift version didn't support storyboard yet.
I'm going to support it this afternoon, will notify you if it's ok.
Thanks again!

**Comment by maxhis** [comment]
@wangmchn Good to know. Thanks for your efforts!

**Comment by wangmchn** [comment]
@maxhis 
Supported yet. See demo for more infomation.
But it still need test, tell me whether it works for u.
Thanks! :muscle:

**Comment by maxhis** [comment]
Still not working for me and got the same error. The only difference between my project and your demo is that I am using custom TableViewCell whose Identifier setted in Storyboard. By using `pod 'WMPageController-Swift', :head`, it should import your latest code.

I am wondering if I can use the OC version library in my swift project.

**Comment by maxhis** [comment]
Awesome! It works like a charm. You can update the podspec file, I am using `pod 'WMPageController-Swift', :head` to import your latest code currently.
