### ISSUE TITLE
WMPageController change NavigationBar/TabBar color

### ISSUE THREAD

**Issue by maxhis** [wangmchn/WMPageController-Swift#4]
When embedded `WMPageController` into `UINavigationBarController` or `UITabBarController`, the color of navigation bar/tab bar change to a little bit transparent and dark. The Objective-C version has the same issue, I tested with the demo code.

Still I am using storyboard, if it may be a cause.

**Comment by wangmchn** [comment]
There is a way to solve the problem.
Set `window.backgroundColor = .whiteColor()` in `AppDelegate.swift`

**Comment by maxhis** [comment]
That works in my case. But I'm wondering if there is some side effect. 

Thanks a lot.

**Comment by wangmchn** [comment]
Perhaps....
I will try to improve it.
