### ISSUE TITLE
Crashed in PageController.removeSuperfluousViewControllersIfNeeded()

### ISSUE THREAD

**Issue by maxhis** [wangmchn/WMPageController-Swift#5]
我的Controller层级是这样的：

```
PageController
    |
    -- UICollectionViewController  --> DetailViewController
    -- UICollectionViewController
    -- UICollectionViewController
```

当反复进入 `DetailViewController`再返回时会出现crash，具体代码在 `PageController.removeSuperfluousViewControllersIfNeeded()  line 337`，能帮忙看看是什么原因导致的吗？非常感谢！

![](http://7xpj55.com1.z0.glb.clouddn.com/iorz0drm8yis8m2t9.png)

**Comment by wangmchn** [comment]
Fixed.
这里粗心地调用了错误的方法，抱歉~

**Comment by maxhis** [comment]
还以为是cycle retain，但又看到 [weak self]了，我iOS新手水平有限。

记得更新podspec哦，多谢！
